name: CodeAura

on:
  push:
    branches:
      - main  # Adjust this branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Firebase Tools
        run: npm install -g firebase-tools

      - name: Login to Firebase
        run: firebase login --no-localhost

      - name: Deploy to Firebase
        run: firebase deploy --token "${{ secrets.FIREBASE_TOKEN }}" --non-interactive --only hosting
